import type { Metadata } from "next";
import "./globals.css";
import Header from "./header/page";
import Layout from "./components/Layout";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Layout>{children}</Layout> {/* This renders your sidebar + content */}
      </body>
    </html>
  );
}
